export enum REGIONAL_POKEDEXES {
  KANTO = "Kanto",
  KANTO_NEW_POKEDEX = "Kanto New Pokédex",
  NEW_POKEDEX = "New Pokédex",
  JOHTO = "Johto",
  HOENN_GENERATION_III = "Hoenn (Generation III)",
  HOENN_GENERATION_VI = "Hoenn (Generation VI)",
  SINNOH = "Sinnoh",
  ENHANCED_SINNOH = "Enhanced Sinnoh",
  UNOVA_BLACK_AND_WHITE = "Unova (Black and White)",
  UNOVA_BLACK_2_AND_WHITE_2 = "Unova (Black 2 and White 2)",
  KALOS = "Kalos",
  ALOLA_SUN_AND_MOON = "Alola (Sun and Moon)",
  ALOLA_ULTRA_SUN_AND_ULTRA_MOON = "Alola (Ultra Sun and Ultra Moon)",
  GALAR = "Galar",
  THE_ISLE_OF_ARMOR = "The Isle of Armor",
  THE_CROWN_TUNDRA = "The Crown Tundra",
  HISUI = "Hisui",
  PALDEA = "Paldea",
  KITAKAMI = "Kitakami",
}
