import { REGIONAL_POKEDEXES } from "../_enums/regional-pokedexes.enum";

export const REGIONAL_POKEDEXES_LIST: REGIONAL_POKEDEXES[] = [
  REGIONAL_POKEDEXES.KANTO,
  REGIONAL_POKEDEXES.KANTO_NEW_POKEDEX,
  REGIONAL_POKEDEXES.NEW_POKEDEX,
  REGIONAL_POKEDEXES.JOHTO,
  REGIONAL_POKEDEXES.HOENN_GENERATION_III,
  REGIONAL_POKEDEXES.HOENN_GENERATION_VI,
  REGIONAL_POKEDEXES.SINNOH,
  REGIONAL_POKEDEXES.ENHANCED_SINNOH,
  REGIONAL_POKEDEXES.UNOVA_BLACK_AND_WHITE,
  REGIONAL_POKEDEXES.UNOVA_BLACK_2_AND_WHITE_2,
  REGIONAL_POKEDEXES.KALOS,
  REGIONAL_POKEDEXES.ALOLA_SUN_AND_MOON,
  REGIONAL_POKEDEXES.ALOLA_ULTRA_SUN_AND_ULTRA_MOON,
  REGIONAL_POKEDEXES.GALAR,
  REGIONAL_POKEDEXES.ISLE_OF_ARMOR,
  REGIONAL_POKEDEXES.CROWN_TUNDRA,
  REGIONAL_POKEDEXES.HISUI,
  REGIONAL_POKEDEXES.KITAKAMI,
];

export type RegionalPokedexData = {
  id: REGIONAL_POKEDEXES;
  url: string;
  section?: string;
  format?: "";
};

export const REGIONAL_POKEDEXES_DATA: {
  [pokedex in REGIONAL_POKEDEXES]?: RegionalPokedexData;
} = {
  [REGIONAL_POKEDEXES.KANTO]: {
    id: REGIONAL_POKEDEXES.KANTO,
    url: "https://bulbapedia.bulbagarden.net/w/index.php?title=List_of_Pok%C3%A9mon_by_Kanto_Pok%C3%A9dex_number&action=edit",
    section: "===Red, Blue, Yellow, FireRed, and LeafGreen edition",
  },
};
