import { TYPES } from "../_enums/types.enum";

export const TYPES_LIST: TYPES[] = [
  TYPES.NORMAL,
  TYPES.FIRE,
  TYPES.WATER,
  TYPES.ELECTRIC,
  TYPES.GRASS,
  TYPES.ICE,
  TYPES.FIGHTING,
  TYPES.POISON,
  TYPES.GROUND,
  TYPES.FLYING,
  TYPES.PSYCHIC,
  TYPES.BUG,
  TYPES.ROCK,
  TYPES.GHOST,
  TYPES.DRAGON,
  TYPES.DARK,
  TYPES.STEEL,
  TYPES.FAIRY,
];
